onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /str_tb/PCout
add wave -noupdate /str_tb/ZHighout
add wave -noupdate /str_tb/ZLowOut
add wave -noupdate /str_tb/MDRout
add wave -noupdate /str_tb/Gra
add wave -noupdate /str_tb/Grb
add wave -noupdate /str_tb/Grc
add wave -noupdate /str_tb/BAout
add wave -noupdate /str_tb/Rin
add wave -noupdate /str_tb/Rout
add wave -noupdate /str_tb/MARin
add wave -noupdate /str_tb/ZHighIn
add wave -noupdate /str_tb/ZLowIn
add wave -noupdate /str_tb/PCin
add wave -noupdate /str_tb/MDRin
add wave -noupdate /str_tb/IRin
add wave -noupdate /str_tb/IRout
add wave -noupdate /str_tb/Yin
add wave -noupdate /str_tb/Yout
add wave -noupdate /str_tb/IncPC
add wave -noupdate /str_tb/Read
add wave -noupdate /str_tb/Write
add wave -noupdate /str_tb/MARout
add wave -noupdate /str_tb/LOin
add wave -noupdate /str_tb/HIin
add wave -noupdate /str_tb/RCout
add wave -noupdate /str_tb/R3in
add wave -noupdate /str_tb/R2in
add wave -noupdate /str_tb/R1in
add wave -noupdate /str_tb/R5in
add wave -noupdate /str_tb/R6in
add wave -noupdate /str_tb/CONin
add wave -noupdate /str_tb/clock
add wave -noupdate /str_tb/clear
add wave -noupdate /str_tb/OutPortIn
add wave -noupdate /str_tb/InPortIn
add wave -noupdate /str_tb/Present_state
add wave -noupdate /str_tb/PCout
add wave -noupdate /str_tb/ZHighout
add wave -noupdate /str_tb/ZLowOut
add wave -noupdate /str_tb/MDRout
add wave -noupdate /str_tb/Gra
add wave -noupdate /str_tb/Grb
add wave -noupdate /str_tb/Grc
add wave -noupdate /str_tb/BAout
add wave -noupdate /str_tb/Rin
add wave -noupdate /str_tb/Rout
add wave -noupdate /str_tb/MARin
add wave -noupdate /str_tb/ZHighIn
add wave -noupdate /str_tb/ZLowIn
add wave -noupdate /str_tb/PCin
add wave -noupdate /str_tb/MDRin
add wave -noupdate /str_tb/IRin
add wave -noupdate /str_tb/IRout
add wave -noupdate /str_tb/Yin
add wave -noupdate /str_tb/Yout
add wave -noupdate /str_tb/IncPC
add wave -noupdate /str_tb/Read
add wave -noupdate /str_tb/Write
add wave -noupdate /str_tb/MARout
add wave -noupdate /str_tb/LOin
add wave -noupdate /str_tb/HIin
add wave -noupdate /str_tb/RCout
add wave -noupdate /str_tb/R3in
add wave -noupdate /str_tb/R2in
add wave -noupdate /str_tb/R1in
add wave -noupdate /str_tb/R5in
add wave -noupdate /str_tb/R6in
add wave -noupdate /str_tb/CONin
add wave -noupdate /str_tb/clock
add wave -noupdate /str_tb/clear
add wave -noupdate /str_tb/OutPortIn
add wave -noupdate /str_tb/InPortIn
add wave -noupdate /str_tb/Present_state
add wave -noupdate -radix hexadecimal /str_tb/STR_DUT/R3/BusMuxIn
add wave -noupdate /str_tb/STR_DUT/R3/enable
add wave -noupdate -radix hexadecimal /str_tb/STR_DUT/IR/BusMuxIn
add wave -noupdate /str_tb/STR_DUT/IR/enable
add wave -noupdate -radix hexadecimal {/str_tb/STR_DUT/RAM/memory[52]}
add wave -noupdate {/str_tb/STR_DUT/RAM/memory[51]}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {22301 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 209
configure wave -valuecolwidth 196
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {184513 ps}
